fix(ci): avoid actions/setup-node cache failure `actions/setup-node@v4` requires pnpm cache directory to exist, or will throw error in post-script:
```
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

The pnpm store directory won't be initialized without a `pnpm install`,
so manually create it to avoid this error.